{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_alluredemo1.py:24: AssertionError"}, "description": "this test fails", "start": 1604324654433, "stop": 1604324654433, "uuid": "6f718808-7767-40e9-bc47-679af4af66b2", "historyId": "9e8d23832460ad3c87806390b91ae72c", "testCaseId": "d3ba699b3e70ee73490c0d009b152181", "fullName": "test_alluredemo1#test_failure", "labels": [{"name": "suite", "value": "test_alluredemo1"}, {"name": "host", "value": "LAPTOP-UL20B91J"}, {"name": "thread", "value": "5676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo1"}]}